# 头像
avatar: https://wp.pdcong.top/f/pbrhp/icon1.jpg

# 背景
background:
    - /images/background.jpg

# 加载动画
loading: /images/loading.gif

# 主菜单导航
menu:
    主页:
        name: house
        theme: solid
        link: /
    关于:
        name: id-card
        theme: solid
        link: /about
    归档:
        name: box-archive
        theme: solid
        link: /archives
    类别:
        name: bookmark
        theme: solid
        link: /categories
    标签:
        name: tags
        theme: solid
        link: /tags
    导航页:
        name: bars
        theme: solid
        link: /blog

# 主页信息卡片
card:
    enable: true
    description:
        hello
    iconLinks:
        github:
            name: github
            theme: brands
            link: https://github.com/1445982330/
        qq:
            name: qq
            theme: brands
            link: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1445982330&website=www.oicqzone.com
        bilibili:
            name: bilibili
            theme: brands
            link: https://space.bilibili.com/70543500
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
    friendLinks:
        友链: https://pdcong.top/
        # <name>: <link-url>

# 页脚配置
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: true
        code: 粤ICP备2023129249号
        link: https://beian.miit.gov.cn

search:
    enable: true